### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by sion2k** [sonatype/nexus-blobstore-s3#12]
* **What are you trying to do?**
I'm trying to do 'mvn clean install'.

* **What feature or behavior is this required for?**
This should build the plugin but build fails.

* **How could we solve this issue? (Not knowing is okay!)**
I don't see any repos configured in pom.xml. Looks like correct maven repo should be added.

* **Anything else?**
I've tried to add "https://repository.sonatype.org/content/groups/sonatype-public-grid" as repo but it has no org.sonatype.nexus.nexus-components-3.6.0-SNAPSHOT

**Comment by julian3xl** [comment]
change 3.6.0-SNAPSHOT by 3.5.2-01 into the pom.xml and it works.

**Comment by ataylor284** [comment]
Sorry about that.  We've been working on this with a pre-release version of Nexus, and some dependencies on the next version snuck in.  I've removed them from master.  You can still find them on the nexus-3.6 branch.  Expect them to be merged back in when Nexus 3.6 is released.
