### ISSUE TITLE
Support DefaultAWSCredentialsProviderChain

### ISSUE THREAD

**Issue by yv13** [sonatype/nexus-blobstore-s3#30]
* **What are you trying to do?**

The Nexus repo is running in a EC2 instance. We wish to use IAM instance roles / profiles to set the credentials for accessing the S3 bucket.

* **What feature or behavior is this required for?**

To avoid storing AWS credentials in the Nexus config and in `~/.aws/credentials`

* **How could we solve this issue? (Not knowing is okay!)**

Some pointers that might be useful:

http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html

http://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/java-dg-roles.html

* **Anything else?**

**Comment by ataylor284** [comment]
Leaving the credentials blank in the configuration screen will force Nexus to authenticate with the EC2 instance IAM role.
