### ISSUE TITLE
S3 Bucket Policy requires additional permissions for tagging objects to be deleted

### ISSUE THREAD

**Issue by jrbeilke** [sonatype/nexus-blobstore-s3#58]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
Delete or re-deploy an artifact in Nexus S3 blob store

* **What feature or behavior is this required for?**
Soft-deleting blobs in S3

* **How could we solve this issue? (Not knowing is okay!)**
The current S3 bucket policy as noted in the README does not include object tagging actions, which results in failures when attempting to soft-delete an object. Instead of "s3:GetObject", "s3:PutObject", and "s3:DeleteObject" we've been using "s3:GetObject*", "s3:PutObject*", and "s3:DeleteObject*" in our IAM policy so that blobs/objects can be tagged for deletion.

```
{
    "Version": "2012-10-17",
    "Id": "NexusS3BlobStorePolicy",
    "Statement": [
        {
            "Sid": "NexusS3BlobStoreAccess",
            "Effect": "Allow",
            "Principal": {
                "AWS": "<user-arn>"
            },
            "Action": [
                "s3:PutObject*",
                "s3:GetObject*",
                "s3:DeleteObject*",
                "s3:ListBucket",
                "s3:GetLifecycleConfiguration",
                "s3:PutLifecycleConfiguration"
            ],
            "Resource": [
                "arn:aws:s3:::<s3-bucket-name>",
                "arn:aws:s3:::<s3-bucket-name>/*"
            ]
        }
    ]
}
```

* **Anything else?**
Not sure if this repo is still being updated now that the plugin is part of Nexus, but wanted to open an issue here so others were aware.

**Comment by ataylor284** [comment]
Fixed by https://github.com/sonatype/nexus-blobstore-s3/pull/60
